server: 
   port: 80
   servlet: 
      context-path: /temperature

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temperature
    username: root
    password: 25262728
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug   
        type:
          descriptor:
            sql:
              BasicBinder: trace      
